# -------------------------------------------------------
# Resource Group
# -------------------------------------------------------

resource "azurerm_resource_group" "this" {
  location = var.location
  name     = "rg-aca-${var.product-name}"
  tags     = var.tags
}

# -------------------------------------------------------
# Container App Environment — VNet-injected, workload profiles
#
# The environment is placed in the delegated container-apps
# subnet of the spoke VNet. DNS queries are forwarded to the
# hub Private DNS Resolver so privatelink zones resolve
# without per-spoke zone links.
# -------------------------------------------------------

resource "azurerm_container_app_environment" "this" {
  name                = "cae-${var.product-name}"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tags                = var.tags

  log_analytics_workspace_id     = var.log_analytics_workspace_id
  infrastructure_subnet_id       = var.subnet_id
  internal_load_balancer_enabled = var.internal_load_balancer_enabled
  zone_redundancy_enabled        = var.zone_redundancy_enabled

  # Workload-profiles environment: "Consumption" maps to serverless (pay-per-use).
  # maximum_count and minimum_count must be set to 0 explicitly — Azure returns 0
  # for Consumption profiles, and omitting them causes a perpetual diff.
  workload_profile {
    name                  = "Consumption"
    workload_profile_type = "Consumption"
    maximum_count         = 0
    minimum_count         = 0
  }

  # infrastructure_resource_group_name is auto-generated by Azure (e.g.
  # "ME_cae-fbe_rg-aca-fbe_swedencentral"). It is a ForceNew attribute, so
  # letting Terraform detect drift on it would destroy and recreate the
  # environment on every plan.
  lifecycle {
    ignore_changes = [infrastructure_resource_group_name]
  }
}

# -------------------------------------------------------
# Container App
#
# The pull identity (externally created, ABAC-scoped by the
# ACR module to the target repository) is attached here.
# No broad AcrPull role — access is limited to the specific
# repository via the ABAC condition on the role assignment.
# -------------------------------------------------------

resource "azurerm_container_app" "this" {
  name                         = "ca-${var.product-name}"
  container_app_environment_id = azurerm_container_app_environment.this.id
  resource_group_name          = azurerm_resource_group.this.name
  revision_mode                = "Single"
  workload_profile_name        = "Consumption"
  tags                         = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [var.pull_identity_id]
  }

  # Authenticate to the private ACR using the managed identity (no password).
  # The identity must already have the ABAC repository-scoped pull role.
  registry {
    server   = var.acr_login_server
    identity = var.pull_identity_id
  }

  template {
    min_replicas = var.min_replicas
    max_replicas = var.max_replicas

    container {
      name   = var.container_name
      image  = var.image
      cpu    = var.cpu
      memory = var.memory

      dynamic "env" {
        for_each = var.env_vars
        content {
          name  = env.key
          value = env.value
        }
      }
    }
  }

  ingress {
    external_enabled = true
    target_port      = var.target_port

    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }

  # Terraform manages the Container App scaffold (environment, identity, registry
  # credential) but not the running workload. Image updates, scaling tweaks, and
  # env-var changes after first deploy are owned by CI/CD pipelines.
  lifecycle {
    ignore_changes = [
      # Image and workload config are managed by CI/CD after first deploy.
      template,
      # Azure normalizes the managed-identity resource ID casing (resourcegroups
      # vs resourceGroups) in API responses, causing a perpetual diff on registry.identity.
      registry,
    ]
  }
}
